#!/usr/bin/env bash

start() {
    mkdir -p /etc/docker-gen/templates/
    cp ~/mooc_capstone_public/nginx.tmpl /etc/docker-gen/templates/nginx.tmpl
    docker-compose -f ~/mooc_capstone_public/docker-compose.yml up
}

stop() {
    docker-compose down
    # example: killproc program_name
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0