#!/usr/bin/env bash

start() {
	mkdir -p /etc/docker-gen/templates/
	cp /vizit/nginx.tmpl /etc/docker-gen/templates/nginx.tmpl
	docker-compose -f /vizit/docker-compose.yml up
}

stop() {
    docker-compose down
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
