# Load functions and libraries:
devtools::load_all()

source("video_module/videoModule.R")
source("video_module/videoModuleUI.R")
source("overview_module/overviewModule.R")
source("overview_module/overviewModuleUI.R")
source("linkpage_module/linkpageModule.R")
source("linkpage_module/linkpageModuleUI.R")
source("demographics_module/demographicsModule.R")
source("demographics_module/demographicsModuleUI.R")
source("forum_module/forumModule.R")
source("forum_module/forumModuleUI.R")
source("problem_module/problemModule.R")
source("problem_module/problemModuleUI.R")
